image: beevelop/ionic:latest
stages:
#  - build_web
#  - deploy_android
  - deploy_ios

# before_script:
#     - npm update
#     - npm install
  
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    
# build_web:
#   stage: build_web
#   only:
#       - master
#   script:
#     - ionic build 

# build_android:
#   stage: deploy_android
#   only:
#     - master
#   script:
#     - ls
#     - ionic cordova platform rm android
#     - ionic cordova platform add android
#     - ionic cordova build android
#     - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -
#       F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivodigitalappfront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload

build_ios:
  
  stage: deploy_ios
  only:
    - master
  image: sickcodes/docker-osx:naked

  before_script:
    #- /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    #- curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/node-latest.pkg" && sudo installer -store -pkg "$HOME/node-latest.pkg" -target "/"
    #- pkgin -y install nodejs
    - curl "https://nodejs.org/dist/v14.17.3/node-v14.17.3.pkg" > "$HOME/node-v14.17.3.pkg"
    - ls /usr/sbin/installer
    - /usr/sbin/installer -pkg "$HOME/node-v14.17.3.pkg" -target /
    - /usr/sbin/installer 
    #- /home/linuxbrew/.linuxbrew/bin/brew install node
    #- sudo ln -s /usr/bin/nodejs /usr/bin/node
    #- export PATH="$PATH:/usr/local/bin"
    - npm install -g grunt
    - npm update
    - npm install
  script:
    - ls
    #- ionic cordova platform rm ios
    #- ionic cordova platform add ios
    #- ionic cordova build ios
    #- curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivodigitalappfront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload


