<<<<<<< HEAD
image: beevelop/ionic:latest
=======
image: sickcodes/docker-osx
services:
- beevelop/ionic:latest
- node
>>>>>>> 9bf072b1874d364a688c26f41bfb1d6caa787dcc
stages:
  - test
  - deploy
  - deploy_ios

before_script:
    - npm update
    - npm install
  
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    
build_web:
  stage: test
  only:
      - master
  script:
    - ionic build 

build_android:
  stage: deploy
  only:
    - master
  script:
    - ls
    - ionic cordova platform rm android
    - ionic cordova platform add android
    - ionic cordova build android
    - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivofront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload

build_ios:
  
  stage: deploy_ios
  only:
    - master
  image: sickcodes/docker-osx

  before_script:
    - brew install node
    - npm update
    - npm install
  script:
    - ls
    - ionic cordova platform rm ios
    - ionic cordova platform add ios
    - ionic cordova build ios
    - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivofront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload


