image: beevelop/ionic:latest
stages:
#  - build_web
#  - deploy_android
  - deploy_ios

# before_script:
#     - npm update
#     - npm install
  
cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - node_modules/
    
# build_web:
#   stage: build_web
#   only:
#       - master
#   script:
#     - ionic build 

# build_android:
#   stage: deploy_android
#   only:
#     - master
#   script:
#     - ls
#     - ionic cordova platform rm android
#     - ionic cordova platform add android
#     - ionic cordova build android
#     - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -
#       F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivodigitalappfront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload

build_ios:
  
  stage: deploy_ios
  only:
    - master
  image: sickcodes/docker-osx

  before_script:
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - /home/linuxbrew/.linuxbrew/bin/brew install node
    - ls /home/linuxbrew/.linuxbrew/
    - ls /home/linuxbrew/.linuxbrew/etc/
    - ls /home/linuxbrew/.linuxbrew/bin/
    - /home/linuxbrew/.linuxbrew/bin/npm update
    - /home/linuxbrew/.linuxbrew/bin/npm install
  script:
    - ls
    - ionic cordova platform rm ios
    - ionic cordova platform add ios
    - ionic cordova build ios
    - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -F initial_comment="Hola equipo! dejo el ultimo APK (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivodigitalappfront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload


