image: niklasmerz/ionic-build-android-ci-docker:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - npm install
          - bower install --allow-root
          - ionic config build
          - ionic platform add android
          - ionic build android