---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ionic
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  deploy:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6: {}
    - script@1:
        title: Do anything with Script step
    - certificate-and-profile-installer@1: {}
    - npm@1:
        inputs:
        - command: install
    - karma-jasmine-runner@0: {}
    - generate-cordova-build-configuration@0: {}
    - ionic-archive@2:
        inputs:
        - platform: "$IONIC_PLATFORM"
        - target: emulator
    - deploy-to-bitrise-io@2: {}
  primary:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6: {}
    - script@1:
        title: Do anything with Script step
    - npm@1:
        inputs:
        - command: install
    - karma-jasmine-runner@0: {}
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    stack: osx-xcode-13.1.x
    machine_type_id: g2.4core
app:
  envs:
  - opts:
      is_expand: false
    IONIC_PLATFORM: ios,android
