.deploy: &deploy
  stage: deploy
  cache:
    # speed up packaging by sharing cache amongst multiple deploy jobs of the same commit
    key: "deploy-$CI_COMMIT_SHORT_SHA"
    paths:
      - platforms/
      - plugins/
  before_script:
    # workaround Xcode not downloading updated profiles
    - rm -fr ~/Library/MobileDevice/Provisioning\ Profiles/
    - echo "$BUILD_CONFIG" | tr -d '\r' > build.json
  after_script:
    - rm build.json
    - cp $OUTPUT_PATH.$FILE_TYPE $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$FILE_TYPE
  artifacts:
    name:
    paths:
      - $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$FILE_TYPE
    expire_in: 7 days
  tags:
    - macOS
  when: manual
  
deploy:android:debug:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: android
    FILE_TYPE: apk
    OUTPUT_PATH: platforms/android/app/build/outputs/apk/debug/app-debug
  script:
    - npm ci
    - ionic cordova build android --debug
deploy:android:release:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: android
    FILE_TYPE: apk
    OUTPUT_PATH: platforms/android/app/build/outputs/apk/debug/app-debug.apk
    
  script:
    - npm ci
    - ionic cordova platform add android
    - ionic cordova build android -v
    - pwd
    - ls platforms/android/app/build/outputs/apk/debug/app-debug.apk
    - curl --request POST -F token="${SLACK_CHANNEL_ACCESS_TOKEN}" -F channels="${SLACK_CHANNEL_ID}" -F initial_comment="Hola equipo! dejo el ultimo APK 🚀 (compilacion de test)" -F "file=@/builds/equipo-de-desarrollo-efectivo-digital/efectivofront/platforms/android/app/build/outputs/apk/debug/app-debug.apk" https://slack.com/api/files.upload
deploy:ios:debug:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: iOS
    FILE_TYPE: ipa
    OUTPUT_PATH: platforms/ios/build/device/my-app
  script:
    - npm ci
    - ionic cordova build ios --debug
deploy:ios:release:
  <<: *deploy
  environment:
    name: production
  variables:
    PLATFORM: iOS
    FILE_TYPE: ipa
    OUTPUT_PATH: platforms/ios/build/device/my-app
  script:
    - npm ci
    - ionic cordova build ios --release
